In [4]:
# Create dataframe from a list

import pandas as pd

In [ ]:
numbers = [1, 2, 3, 4, 5, 6]

In [5]:
pd.DataFrame(numbers)

NameError: name 'numbers' is not defined

In [ ]:
data = [["Jhon",  23], ["Mary", 18], ["Jhon", 31]]

In [ ]:
pd.DataFrame(data)

      0   1
0  Jhon  23
1  Mary  18
2  Jhon  31

In [ ]:
pd.DataFrame(data, columns = ["name", "age"])

   name  age
0  Jhon   23
1  Mary   18
2  Jhon   31

In [ ]:
pd.DataFrame(data, columns = ["name", "age"], index = ["id1", "id2", "id3"])

     name  age
id1  Jhon   23
id2  Mary   18
id3  Jhon   31